name: todone
description: "Another FOSS ToDo app"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  adaptive_theme: ^3.7.0
  flutter:
    sdk: flutter
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
