name: todone
description: "Another FOSS ToDo app"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  adaptive_theme: ^3.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.6.3
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.14
  slang_build_runner: ^4.4.0
  flutter_native_splash: ^2.4.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
